# name | OnCalendar | python module
upgrade-adoption|*-*-* *:11,31,51:00|upgrade_adoption_watcher.py
our-nodes|*-*-* *:17:00|our_nodes_watcher.py
devshard|*-*-* *:19:00|devshard_watcher.py
gateways|*-*-* 1,3,5,7,9,11,13,15,17,19,21,23:47:00|gateway_watcher.py
new-hosts|*-*-* *:07,37:00|new_host_bot.py
model-coefficients|*-*-* *:43:00|model_coefficients_watcher.py
glamsterdam|*-*-* 00,06,12,18:23:00|glamsterdam_watcher.py
exclusions|*-*-* *:02/5:00|excluded_watcher.py
escrow-balances|*-*-* *:11,26,41,56:00|escrow_balance_watcher.py
chain-load|*-*-* *:03/5:00|chain_load_watcher.py
chain-halt|*-*-* *:01/5:00|chain_halt_watcher.py
bridge-stale|*-*-* *:04/5:00|bridge_stale_watcher.py
bridge-burn|*-*-* *:02/5:00|bridge_burn_watcher.py
